"""empty message

Revision ID: 4fdf0f18b888
Revises: 63a76ec16d78
Create Date: 2022-05-25 17:34:59.578983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdf0f18b888'
down_revision = '63a76ec16d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nome'), 'categoria', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categoria_nome'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
