"""empty message

Revision ID: 63a76ec16d78
Revises: 
Create Date: 2022-05-24 20:36:46.175736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a76ec16d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('url_jogo', sa.String(), nullable=True),
    sa.Column('url_video', sa.String(), nullable=True),
    sa.Column('url_imagem', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogo_categoria'), 'jogo', ['categoria'], unique=False)
    op.create_index(op.f('ix_jogo_descricao'), 'jogo', ['descricao'], unique=False)
    op.create_index(op.f('ix_jogo_nome'), 'jogo', ['nome'], unique=False)
    op.create_index(op.f('ix_jogo_url_imagem'), 'jogo', ['url_imagem'], unique=False)
    op.create_index(op.f('ix_jogo_url_jogo'), 'jogo', ['url_jogo'], unique=False)
    op.create_index(op.f('ix_jogo_url_video'), 'jogo', ['url_video'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('nome_completo', sa.String(length=120), nullable=True),
    sa.Column('data_de_nascimento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.Column('pais', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_de_nascimento'), 'user', ['data_de_nascimento'], unique=False)
    op.create_index(op.f('ix_user_estado'), 'user', ['estado'], unique=False)
    op.create_index(op.f('ix_user_nome_completo'), 'user', ['nome_completo'], unique=False)
    op.create_index(op.f('ix_user_pais'), 'user', ['pais'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Float(), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.Column('qnt_util', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_estrelas'), 'avaliacao', ['estrelas'], unique=False)
    op.create_index(op.f('ix_avaliacao_qnt_util'), 'avaliacao', ['qnt_util'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacao_qnt_util'), table_name='avaliacao')
    op.drop_index(op.f('ix_avaliacao_estrelas'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_pais'), table_name='user')
    op.drop_index(op.f('ix_user_nome_completo'), table_name='user')
    op.drop_index(op.f('ix_user_estado'), table_name='user')
    op.drop_index(op.f('ix_user_data_de_nascimento'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_jogo_url_video'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_url_jogo'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_url_imagem'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_nome'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_descricao'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_categoria'), table_name='jogo')
    op.drop_table('jogo')
    # ### end Alembic commands ###
