"""empty message

Revision ID: ae3b439674a0
Revises: 4fdf0f18b888
Create Date: 2022-05-27 08:33:50.530526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3b439674a0'
down_revision = '4fdf0f18b888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voto_util',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voto_util')
    # ### end Alembic commands ###
