"""tirando unique

Revision ID: e4f9ab13c5ed
Revises: fdc6711591bf
Create Date: 2022-03-27 23:23:03.143580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f9ab13c5ed'
down_revision = 'fdc6711591bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jogo_descricao', table_name='jogo')
    op.create_index(op.f('ix_jogo_descricao'), 'jogo', ['descricao'], unique=False)
    op.drop_index('ix_jogo_nome', table_name='jogo')
    op.create_index(op.f('ix_jogo_nome'), 'jogo', ['nome'], unique=False)
    op.drop_index('ix_jogo_url_imagem', table_name='jogo')
    op.create_index(op.f('ix_jogo_url_imagem'), 'jogo', ['url_imagem'], unique=False)
    op.drop_index('ix_jogo_url_jogo', table_name='jogo')
    op.create_index(op.f('ix_jogo_url_jogo'), 'jogo', ['url_jogo'], unique=False)
    op.drop_index('ix_jogo_url_video', table_name='jogo')
    op.create_index(op.f('ix_jogo_url_video'), 'jogo', ['url_video'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogo_url_video'), table_name='jogo')
    op.create_index('ix_jogo_url_video', 'jogo', ['url_video'], unique=False)
    op.drop_index(op.f('ix_jogo_url_jogo'), table_name='jogo')
    op.create_index('ix_jogo_url_jogo', 'jogo', ['url_jogo'], unique=False)
    op.drop_index(op.f('ix_jogo_url_imagem'), table_name='jogo')
    op.create_index('ix_jogo_url_imagem', 'jogo', ['url_imagem'], unique=False)
    op.drop_index(op.f('ix_jogo_nome'), table_name='jogo')
    op.create_index('ix_jogo_nome', 'jogo', ['nome'], unique=False)
    op.drop_index(op.f('ix_jogo_descricao'), table_name='jogo')
    op.create_index('ix_jogo_descricao', 'jogo', ['descricao'], unique=False)
    # ### end Alembic commands ###
