"""jogos table

Revision ID: fdc6711591bf
Revises: 
Create Date: 2022-03-27 22:52:38.530484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc6711591bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('url_jogo', sa.String(), nullable=True),
    sa.Column('url_video', sa.String(), nullable=True),
    sa.Column('url_imagem', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogo_categoria'), 'jogo', ['categoria'], unique=False)
    op.create_index(op.f('ix_jogo_descricao'), 'jogo', ['descricao'], unique=True)
    op.create_index(op.f('ix_jogo_nome'), 'jogo', ['nome'], unique=True)
    op.create_index(op.f('ix_jogo_url_imagem'), 'jogo', ['url_imagem'], unique=True)
    op.create_index(op.f('ix_jogo_url_jogo'), 'jogo', ['url_jogo'], unique=True)
    op.create_index(op.f('ix_jogo_url_video'), 'jogo', ['url_video'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogo_url_video'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_url_jogo'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_url_imagem'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_nome'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_descricao'), table_name='jogo')
    op.drop_index(op.f('ix_jogo_categoria'), table_name='jogo')
    op.drop_table('jogo')
    # ### end Alembic commands ###
